import Head from 'next/head'
import SecretBox from '../components/SecretBox'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import utilStyles from '../styles/utils.module.scss'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Link href='/posts/first-post'><a style={{ color: "red" }}>Go to the first post</a></Link>
				<ul>
					{new Array(100).fill('').map((_, i) => {
						return (
							<ul key={i}>
								<Link href={`/posts/${i + 1}`}>
									<a className={utilStyles.link}>{`Open post №${i + 1}`}</a>
								</Link>
							</ul>
						)
					})}
				</ul>
			</main>
		</div>
	)
}
